function [T1Opt, T2Opt] = optCtrl(obj, t, y, deriv, T1Mode, T2Mode, dims)
% uOpt = optCtrl(obj, t, y, deriv, uMode, dims)

%% Input processing
if nargin < 5
  T1Mode = 'min';
end

if nargin < 6
  T2Mode = 'min';
end

if nargin < 7
  dims = 1:obj.nx;
end

if ~iscell(deriv)
  deriv = num2cell(deriv);
end

%% Optimal control
if strcmp(T1Mode, 'max')
  T1Opt = ((deriv{dims==2}*(-1/obj.m)*(sin(x{dims==5})))>=0)*obj.T1Max +...
          ((deriv{dims==2}*(-1/obj.m)*(sin(x{dims==5})))<0)*obj.T1Min +...
          ((deriv{dims==4}*((1/obj.m)*cos(x{dims==5})))>=0)*obj.T1Max +...
          ((deriv{dims==4}*((1/obj.m)*cos(x{dims==5})))<0)*obj.T1Min +...
          ((deriv{dims==6}*(-obj.l/obj.Iyy))>=0)*obj.T1Max +...
          ((deriv{dims==6}*(-obj.l/obj.Iyy))<0)*obj.T1Min;
elseif strcmp(T1Mode, 'min')
  T1Opt = ((deriv{dims==2}*(-1/obj.m)*(sin(x{dims==5})))>=0)*obj.T1Min +...
          ((deriv{dims==2}*(-1/obj.m)*(sin(x{dims==5})))<0)*obj.T1Max +...
          ((deriv{dims==4}*((1/obj.m)*cos(x{dims==5})))>=0)*obj.T1Min +...
          ((deriv{dims==4}*((1/obj.m)*cos(x{dims==5})))<0)*obj.T1Max +...
          ((deriv{dims==6}*(-obj.l/obj.Iyy))>=0)*obj.T1Min +...
          ((deriv{dims==6}*(-obj.l/obj.Iyy))<0)*obj.T1Max;
else
  error('Unknown T1Mode!')
end

if strcmp(T2Mode, 'max')
  T2Opt = ((deriv{dims==2}*(-1/obj.m)*(sin(x{dims==5})))>=0)*obj.T2Max +...
          ((deriv{dims==2}*(-1/obj.m)*(sin(x{dims==5})))<0)*obj.T2Min +...
          ((deriv{dims==4}*((1/obj.m)*cos(x{dims==5})))>=0)*obj.T2Max +...
          ((deriv{dims==4}*((1/obj.m)*cos(x{dims==5})))<0)*obj.T2Min +...
          ((deriv{dims==6}*(obj.l/obj.Iyy))>=0)*obj.T2Max +...
          ((deriv{dims==6}*(obj.l/obj.Iyy))<0)*obj.T2Min;
elseif strcmp(T2Mode, 'min')
  T2Opt = ((deriv{dims==2}*(-1/obj.m)*(sin(x{dims==5})))>=0)*obj.T2Min +...
          ((deriv{dims==2}*(-1/obj.m)*(sin(x{dims==5})))<0)*obj.T2Max +...
          ((deriv{dims==4}*((1/obj.m)*cos(x{dims==5})))>=0)*obj.T2Min +...
          ((deriv{dims==4}*((1/obj.m)*cos(x{dims==5})))<0)*obj.T2Max +...
          ((deriv{dims==6}*(obj.l/obj.Iyy))>=0)*obj.T2Min +...
          ((deriv{dims==6}*(obj.l/obj.Iyy))<0)*obj.T2Max;
else
  error('Unknown T2Mode!')
end

end